// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO52HBW17saX71eYE0jx2QIR0tAqKZPWo',
    appId: '1:87406279015:web:568aa3fefa1d0484fed7c2',
    messagingSenderId: '87406279015',
    projectId: 'giphy-app-b261a',
    authDomain: 'giphy-app-b261a.firebaseapp.com',
    storageBucket: 'giphy-app-b261a.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeTe0Eoso7wRIf6ez_FFKiVFeQ4qEb90s',
    appId: '1:87406279015:ios:13e7282dfa658614fed7c2',
    messagingSenderId: '87406279015',
    projectId: 'giphy-app-b261a',
    storageBucket: 'giphy-app-b261a.appspot.com',
    iosBundleId: 'com.example.giphyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO52HBW17saX71eYE0jx2QIR0tAqKZPWo',
    appId: '1:87406279015:web:7acdbd895dcbd94efed7c2',
    messagingSenderId: '87406279015',
    projectId: 'giphy-app-b261a',
    authDomain: 'giphy-app-b261a.firebaseapp.com',
    storageBucket: 'giphy-app-b261a.appspot.com',
  );
}
